const tokenMap = {
  "Airtable": "upn:airtable:auth:",
  "AliExpress": "upn:aliexpress:auth:",
  "Brex Dashboard": "upn:brex:auth:",
  "Checkr Dashboard": "upn:checkr:auth:",
  "Clerky": "upn:clerky:auth:",
  "Deel": "upn:deel:auth:",
  "Docker": "upn:docker:auth:",
  "Fantastical": "upn:fantastical:auth:",
  "Fantastical for iOS": "upn:fantastical:auth:",
  "Fiverr": "upn:fiverr:auth:",
  "GlassDoor": "upn:glassdoor:auth:",
  "Google Chrome": "upn:google-chrome:auth:",
  "GRID": "upn:getgridapp:auth:",
  "Guild.xyz": "upn:guildxyz:auth:",
  "Gusto": "upn:gusto:auth:",
  "iOS": "upn:ios:auth:",
  "iOS Account Manager": "upn:ios:auth:",
  "Looker Studio": "upn:lookerstudio:auth:",
  "Loom": "upn:loom:auth:",
  "Microsoft Google Play Android Developer Account": "upn:microsoft-google-play-android-developer-account:auth:",
  "Miro": "upn:miro:auth:",
  "Navigraph": "upn:navigraph:auth:",
  "Next Insurance": "upn:nextinsurance:auth:",
  "Notion": "upn:notion:auth:",
  "Notion2Charts": "upn:notion2charts:auth:",
  "OpenAI": "upn:openai:auth:",
  "Rows": "upn:rows:auth:",
  "Slack": "upn:slack:auth:",
  "Slidebean": "upn:slidebean:auth:",
  "Super": "upn:superso:auth:",
  "tl;dv": "upn:tldv:auth:",
  "Webflow": "upn:webflow:auth:",
  "Wix": "upn:wix:auth:",
  "WordPress": "upn:wordpress:auth:",
  "ClickUp": "upn:clickup:auth:",
  "15Five": "upn:15five:auth:",
  "Shutterstock": "upn:shutterstock:auth:",
  "The QR Code Generator": "upn:the-qr-code-generator:auth:",
  "Figma": "upn:figma:auth:",
  "Iconscout": "upn:iconscout:auth:",
  "Mobbin": "upn:mobbin:auth:",
  "Leonardo Ai": "upn:leonardoai:auth:",
  "Freepik Company": "upn:freepik:auth:",
  "Envato": "upn:envato:auth:",
  "Freshdesk": "upn:freshdesk:auth:",
  "Android device": "upn:android:auth:",
  "pdfFiller": "upn:pdffiller:auth:",
  "Text Blaze": "upn:textblaze:auth:",
  "User_list": "upn:user-list:auth:",
  "Freshworks": "upn:freshworks:auth:",
  "Calendly": "upn:calendly:auth:",
  "Freshteam": "upn:freshteam:auth:",
  "UEFA": "upn:uefa:auth:",
  "Org Chart by Time is Ltd.": "upn:timeisltd:auth:",
  "BambooHR": "upn:bamboohr:auth:",
  "Google Drive for desktop": "upn:google-drive-desktop:auth:",
  "Workable": "upn:workable:auth:",
  "HeyGen": "upn:heygen:auth:",
  "Reclaim.ai": "upn:reclaimai:auth:",
  "macOS": "upn:macos:auth:",
  "Read Chief Meeting Officer": "upn:read-chief-meeting-officer:auth:",
  "Glassdoor": "upn:glassdoor:auth:",
  "Indeed": "upn:indeed:auth:",
  "Yumpu.com": "upn:yumpu:auth:",
  "Tango": "upn:tango:auth:",
  "WorkGPT for Workspace": "upn:workgpt:auth:",
  "Zoom": "upn:zoom:auth:",
  "Pave": "upn:pave:auth:",
  "Reddit": "upn:reddit:auth:",
  "Grammarly": "upn:grammarly:auth:",
  "Modash.io": "upn:modash:auth:",
  "X": "upn:x:auth:",
  "Atlassian": "upn:atlassian:auth:",
  "Quora": "upn:quora:auth:",
  "PC-auth": "upn:pc-auth:auth:",
  "Ⓣ Text Analytics | text2data.com": "upn:text2data:auth:",
  "New Relic": "upn:newrelic:auth:",
  "Mixpanel": "upn:mixpanel:auth:",
  "Microsoft apps & services": "upn:microsoft-apps-services:auth:",
  "dbt Semantic Layer for Sheets": "upn:dbt:auth:",
  "Quizizz": "upn:quizizz:auth:",
  "Zapier": "upn:zapier:auth:",
  "Yahoo!": "upn:yahoo:auth:",
  "Tally": "upn:tally:auth:",
  "draw.io": "upn:drawio:auth:",
  "Tripadvisor": "upn:tripadvisor:auth:",
  "Stayforlong": "upn:stayforlong:auth:",
  "Trello": "upn:trello:auth:",
  "Flipsnack": "upn:flipsnack:auth:",
  "LinkedIn": "upn:linkedin:auth:",
  "Customer.io": "upn:customerio:auth:",
  "Notion Calendar": "upn:notion:auth:",
  "Zoho Sheet": "upn:zoho:auth:",
  "Semrush": "upn:semrush:auth:",
  "Akiflow": "upn:akiflow:auth:",
  "a5-cf-zt": "upn:a5-cf-zt:auth:",
  "backofficepanel.co CF Zero Trust": "upn:backofficepanelco:auth:",
  "LINE: Free Calls & Messages": "upn:lineme:auth:",
  "Grindr": "upn:grindr:auth:",
  "Twilio": "upn:twilio:auth:",
  "GMass": "upn:gmass:auth:",
  "Right Inbox": "upn:rightinbox:auth:",
  "ZIP Extractor": "upn:zipextractor:auth:",
  "Muck Rack": "upn:muckrack:auth:",
  "Dropbox": "upn:dropbox:auth:",
  "Revolut": "upn:revolut:auth:",
  "Proton": "upn:proton:auth:",
  "CoinMarketCap": "upn:coinmarketcap:auth:",
  "monis.rent": "upn:monisrent:auth:",
  "SamsungCalendar": "upn:samsung:auth:",
  "CloudConnexa": "upn:cloudconnexa:auth:",
  "WPS Office": "upn:wps:auth:",
  "QuillBot": "upn:quillbot:auth:",
  "Evernote": "upn:evernote:auth:",
  "Customer.io Sheet Import": "upn:customerio:auth:",
  "Scribbl Enhanced Recordings": "upn:scribbl:auth:",
  "Samsung Email": "upn:samsung:auth:",
  "Tactiq.io": "upn:tactiqio:auth:",
  "PresenterMedia": "upn:presentermedia:auth:",
  "Canva": "upn:canva:auth:",
  "Windows": "upn:microsoft-windows:auth:",
  "Lalamove": "upn:lalamove:auth:",
  "FPPT.com": "upn:fppt:auth:",
  "Meralco Online": "upn:meralco:auth:",
  "marketing_pages_prod_one_tap": "upn:marketing-pages-prod-one-tap:auth:",
  "project-753894345350": "upn:project-753894345350:auth:",
  "WhatsApp Messenger": "upn:whatsapp:auth:",
  "Vista": "upn:vista:auth:",
  "Nexudus": "upn:nexudus:auth:",
  "Trend": "upn:trend:auth:",
  "JoinBrands": "upn:joinbrands:auth:",
  "Billo": "upn:billo:auth:",
  "Mailspring": "upn:mailspring:auth:",
  "Pinterest": "upn:pinterest:auth:",
  "Estado de Minas": "upn:estadodeminas:auth:",
  "Lucidchart": "upn:lucidchart:auth:",
  "Booking.com": "upn:bookingcom:auth:",
  "GoDaddy Login": "upn:godaddy:auth:",
  "BrowserStack": "upn:browserstack:auth:",
  "Global Poker": "upn:globalpoker:auth:",
  "binance.com": "upn:binance:auth:",
  "AppsFlyer": "upn:appsflyer:auth:",
  "Atlassian Cloud": "upn:atlassian:auth:",
  "project-278686754427": "upn:project-278686754427:auth:",
  "Omnibees": "upn:omnibees:auth:",
  "Uber": "upn:uber:auth:",
  "Match 360": "upn:match360:auth:",
  "vivo Email": "upn:vivoemail:auth:",
  "Power Tools": "upn:upowertools:auth:",
  "Elastic Cloud": "upn:elasticcloud:auth:",
  "Adobe Acrobat": "upn:adobe:auth:",
  "Adobe Stock": "upn:adobe:auth:",
  "VEED": "upn:veed:auth:",
  "Gamma": "upn:gamma:auth:",
  "popai": "upn:popai:auth:",
  "FDR Social Dev Keys App": "upn:fdr-social-dev-keys-app:auth:",
  "G2 Crowd": "upn:g2crowd:auth:",
  "Magical": "upn:magical:auth:",
  "Jusbrasil": "upn:jusbrasil:auth:",
  "fathom.video": "upn:fathomvideo:auth:",
  "Email - Edison Mail": "upn:edisonmail:auth:",
  "Spark": "upn:spark:auth:",
  "cloudHQ": "upn:cloudhq:auth:",
  "Canary Mail": "upn:canarymail:auth:",
  "Mimestream": "upn:mimestream:auth:",
  "Mem": "upn:mem:auth:",
  "Bloks": "upn:bloks:auth:",
  "GTO Wizard": "upn:gtowizard:auth:",
  "Untitled project": "upn:untitled-project:auth:",
  "Coupler.io": "upn:couplerio:auth:",
  "DocHub - PDF Sign & Edit": "upn:dochub:auth:",
  "Bitly": "upn:bitly:auth:",
  "Vrbo": "upn:vrbo:auth:",
  "wps-web-apps": "upn:wps-web-apps:auth:",
  "Skyscanner": "upn:skyscanner:auth:",
  "Nord Account": "upn:nordvpn:auth:",
  "Lumin PDF": "upn:luminpdf:auth:",
  "SimilarWeb.com": "upn:similarweb:auth:",
  "Worldtime Buddy": "upn:worldtimebuddy:auth:",
  "Simplified": "upn:simplified:auth:",
  "Yelp": "upn:yelp:auth:",
  "Screencastify": "upn:screencastify:auth:",
  "Browse AI": "upn:browseai:auth:",
  "Postman": "upn:postman:auth:",
  "SoundCloud": "upn:soundcloud:auth:",
  "Logitech - LIdS": "upn:logitech:auth:",
  "Razer": "upn:razer:auth:",
  "Crowdin": "upn:crowdin:auth:",
  "TeamGantt": "upn:teamgantt:auth:",
  "Make": "upn:make:auth:",
  "Fresh Teams": "upn:freshteams:auth:",
  "SEMrush Position Tracking": "upn:semrush:auth:",
  "Landingi": "upn:landingi:auth:",
  "TikTok": "upn:tiktok:auth:",
  "EZCampaign": "upn:ezcampaign:auth:",
  "Cici": "upn:cici:auth:",
  "Spotify": "upn:spotify:auth:",
  "GetYourGuide": "upn:getyourguide:auth:",
  "Temu": "upn:temu:auth:",
  "Contrast": "upn:contrast:auth:",
  "OpenComp": "upn:opencomp:auth:",
  "Geckoboard": "upn:geckoboard:auth:",
  "March 1st mailmerge": "upn:march-1st-mailmerge:auth:",
  "DocuSign": "upn:docusign:auth:",
  "Limitless AI": "upn:limitlessai:auth:",
  "GGPass": "upn:ggpass:auth:",
  "Survicate": "upn:survicate:auth:",
  "ZeroBounce": "upn:zerobounce:auth:",
  "Livestorm": "upn:livestorm:auth:",
  "Blastness Booking G Sign-in": "upn:blastness:auth:",
  "APP TOP1": "upn:apptop1:auth:",
  "howly": "upn:howly:auth:",
  "Trustpilot": "upn:trustpilot:auth:",
  "Google I/O": "upn:google-io:auth:",
  "Typeform": "upn:typeform:auth:",
  "Viator": "upn:viator:auth:",
  "Form Approvals": "upn:form-approvals:auth:",
  "Gmail_Users": "upn:gmail-users:auth:",
  "NordLayer": "upn:nordvpn:auth:",
  "Public Sector Connect": "upn:public-sector-connect:auth:",
  "Medium": "upn:medium:auth:",
  "Project Default Service Account": "upn:project-default-service-account:auth:",
  "Expedia, Inc.": "upn:expedia:auth:",
  "iLovePDF": "upn:ilovepdf:auth:",
  "foodpanda": "upn:foodpanda:auth:",
  "Binance": "upn:binance:auth:",
  "Shopee": "upn:shopee:auth:",
  "TasksBoard": "upn:tasksboard:auth:",
  "dupdub": "upn:dupdub:auth:",
  "ONE store": "upn:onestore:auth:",
  "Agoda": "upn:agoda:auth:",
  "Wordtune": "upn:wordtune:auth:",
  "Google AppSheet": "upn:google-appsheet:auth:",
  "GitLab": "upn:gitlab:auth:",
  "Upwork-SSO": "upn:upwork:auth:",
  "LoopNet": "upn:loopnet:auth:",
  "Veriff Hub": "upn:veriff:auth:",
  "Auth0": "upn:auth0:auth:",
  "Power BI Desktop": "upn:powerbi:auth:",
  "Adobe": "upn:adobe:auth:",
  "Anthropic": "upn:anthropic:auth:",
  "Ubersuggest": "upn:ubersuggest:auth:",
  "Hotjar": "upn:hotjar:auth:",
  "SEMrush Monitoring&Reporting": "upn:semrush:auth:",
  "Surfer": "upn:surfer:auth:",
  "Organic Traffic Insights": "upn:organic-traffic-insights:auth:",
  "Samsung account": "upn:samsung:auth:",
  "Google Workspace Sync for Microsoft Outlook®": "upn:google-workspace-sync:auth:",
  "Motion": "upn:motion:auth:",
  "lit": "upn:lit:auth:",
  "GAM": "upn:gam:auth:",
  "GAM Project Creation": "upn:gam:auth:",
  "ChatGPT": "upn:chatgpt:auth:",
  "Shared Drive Assessment": "upn:shared-drive-assessment:auth:",
  "Superhuman": "upn:superhuman:auth:",
  "Viva Real": "upn:vivareal:auth:",
  "TeamViewer": "upn:teamviewer:auth:",
  "Microsoft Clarity": "upn:microsoft-clarity:auth:",
  "Lightdash Cloud": "upn:lightdash:auth:",
  "LinkedIn Talent Solutions": "upn:linkedin:auth:",
  "Truecaller": "upn:truecaller:auth:",
  "Vimeo": "upn:vimeo:auth:",
  "Fotor": "upn:fotor:auth:",
  "WPT-Global.net": "upn:wpt-global-net:auth:",
  "Riot Accounts": "upn:riot:auth:",
  "Crazy Egg": "upn:crazyegg:auth:",
}

const getTokenUpn = (name, token) => {
  if (tokenMap[name]) {
    return tokenMap[name] + token
  } else {
    return null
  }
}

module.exports = getTokenUpn