version: '3'
services:
  # SERVER AND CLIENT
  app:
    build:
      dockerfile: Dockerfile
    hostname: ${INSTANCE_NAME_APP}
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm start
    environment:
      - PORT=3001
      - SERVER_PORT=3001
      - NEO4J_HTTP_PORT=7474
      - NEO4J_BOLT_PORT=7687
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    ports:
      - 3001:3001 # Server Port
    depends_on:
      - neo4j-db

  # GRAPH DATABASE
  neo4j-db:
    image: neo4j # Use the official Neo4j Docker image
    hostname: ${INSTANCE_NAME_DB}
    volumes:
      - neo4j-data:/data  # Persist Neo4j data
    ports:
      - 7474:7474 # Map container port for HTTP
      - 7687:7687 # Map container port for Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

volumes:
  neo4j-data:
