version: '3'
services:

  # SERVER AND CLIENT
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - PORT:${SERVER_PORT} # Server Port
      - REACT_APP_API_BASE_URL:${REACT_APP_API_BASE_URL} 
    ports:
      - ${SERVER_PORT}:${SERVER_PORT} # Server Port
    env_file:
      - ./.env # Load environment variables from root .env file

  # GRAPH DATABASE
  neo4j-db:
    image: neo4j # Use the official Neo4j Docker image
    hostname: cartographer-neo4j-db-1
    volumes:
      - neo4j-data:/data  # Persist Neo4j data
    ports:
      - ${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT} # Map container port for HTTP
      - ${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT} # Map container port for Bolt
    environment:
      # - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
  
  tunnel:
    image: cloudflare/cloudflared:latest 
    command: "tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}"
    
volumes:
  neo4j-data: # Define the volume for Neo4j data persistence
