version: '3'
services:

  # SERVER
  node-server:
    build:
      context: ./server  # Path to server code
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    command: nodemon app.js localhost 3001
    ports:
      - 3001:3001 # Server Port

  # CLIENT
  react-client:
    build:
      context: ./client  # Path to client code
      dockerfile: Dockerfile
    volumes:
      - ./client:/client:delegated
      - ./client/node_modules:/node_modules
    ports:
      - 3000:3000
    environment:
       - CHOKIDAR_USEPOLLING=true

  # GRAPH DATABASE
  neo4j-db:
    image: neo4j  # Use the official Neo4j Docker image
    hostname: cartographer-neo4j-db-1
    volumes:
      - neo4j-data:/data  # Persist Neo4j data
    ports:
      - 7474:7474  # Map container port for HTTP
      - 7687:7687  # Map container port for Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      
volumes:
  neo4j-data:   # Define the volume for Neo4j data persistence
  